name = "amaes-community-relay"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
REPO_OWNER = "Acads-Tools"
REPO_NAME = "database"
MIN_CLIENT_VERSION = "1.7.5"
REQUIRE_CLIENT_VERSION = "true"
